# Generated by Django 5.1.5 on 2025-05-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_homeslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='button_link',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
