# Generated by Django 5.1.5 on 2025-05-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_homeslider_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(upload_to='contact_banner/')),
            ],
        ),
    ]
