# Generated by Django 5.1.5 on 2025-05-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_aboutusbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs_AboutArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=255)),
                ('main_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quality_title', models.CharField(max_length=255)),
                ('quality_description', models.TextField()),
                ('automation_title', models.CharField(max_length=255)),
                ('automation_description', models.TextField()),
                ('center_title', models.CharField(max_length=255)),
                ('button_text', models.CharField(default='Discover More', max_length=50)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('call_text', models.CharField(max_length=255)),
                ('call_number', models.CharField(max_length=50)),
                ('bg_image', models.ImageField(upload_to='about/')),
                ('man_image', models.ImageField(upload_to='about/')),
                ('shape1', models.ImageField(upload_to='about/')),
                ('shape2', models.ImageField(upload_to='about/')),
                ('call_image', models.ImageField(upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
    ]
