# Generated by Django 5.1.5 on 2025-05-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_aboutus_aboutarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=255)),
                ('main_title', models.CharField(max_length=255)),
                ('button_text', models.CharField(default='Contact Us', max_length=50)),
                ('button_link', models.URLField(default='/contact/', max_length=500)),
                ('shape1', models.ImageField(blank=True, null=True, upload_to='cta/')),
            ],
        ),
    ]
