# Generated by Django 5.1.5 on 2025-05-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_calltoaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoaction',
            name='button_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
