# Generated by Django 5.1.5 on 2025-05-27 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_calltoaction_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_image', models.ImageField(upload_to='choose_us/')),
                ('shape_3', models.ImageField(blank=True, null=True, upload_to='choose_us/')),
                ('shape_4', models.ImageField(blank=True, null=True, upload_to='choose_us/')),
            ],
        ),
        migrations.CreateModel(
            name='ChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.ImageField(help_text='Upload icon image (60x60 recommended)', upload_to='choose_us/icons/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.chooseussection')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
