# Generated by Django 5.1.5 on 2025-05-27 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_chooseussection_chooseusitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='YouTube or video link for popup video', max_length=255)),
                ('video_thumbnail', models.ImageField(help_text='Upload video thumbnail image (recommended size: 570x298)', upload_to='faq/thumbnails/')),
                ('skill1_name', models.CharField(default='T-Shirt Printing', max_length=100)),
                ('skill1_progress', models.PositiveIntegerField(default=75, help_text='Progress in percentage (0-100)')),
                ('skill2_name', models.CharField(default='Branding', max_length=100)),
                ('skill2_progress', models.PositiveIntegerField(default=85, help_text='Progress in percentage (0-100)')),
                ('stat_icon_class', models.CharField(default='flaticon-roll', help_text='Icon CSS class for stat', max_length=50)),
                ('stat_title', models.CharField(default='Smooth Automation', max_length=100)),
                ('stat_count', models.PositiveIntegerField(default=428)),
                ('stat_description', models.CharField(default='Printing Specialist', max_length=150)),
                ('section_subtitle', models.CharField(blank=True, default='FREQUENTLY ASKED QUESTION', max_length=255, null=True)),
                ('section_title', models.CharField(blank=True, default='What Our Clients Ask About Presvila', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_expanded', models.BooleanField(default=False)),
                ('faq_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='backend.faqsection')),
            ],
        ),
    ]
