# Generated by Django 5.1.5 on 2025-05-28 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_practicearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicearea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicearea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
