# Generated by Django 5.1.5 on 2025-05-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_practicearea_created_at_practicearea_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurfaqBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(upload_to='Ourfaq_banner/')),
            ],
        ),
    ]
