# Generated by Django 5.1.5 on 2025-05-29 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_practicearea_created_at_practicearea_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('meta_keys', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='Active', max_length=20)),
                ('codes', models.CharField(help_text='Unique identifier for the category', max_length=50, unique=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, help_text='If this is a subcategory, select the parent category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='backend.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='backend.category'),
        ),
    ]
