# Generated by Django 5.1.5 on 2025-05-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_ourfaqbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='FAQ Question', max_length=500)),
                ('answer', models.TextField(help_text='FAQ Answer')),
                ('is_active', models.BooleanField(default=True, help_text='Display this FAQ on frontend')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('image', models.ImageField(blank=True, help_text='Background/side image (will be resized to 400x218)', null=True, upload_to='faq/section/')),
                ('section_title', models.CharField(default='Presvila Your Printing Company', help_text='Section heading text', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
