# Generated by Django 5.1.5 on 2025-05-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_product_slug_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
