# Generated by Django 5.1.5 on 2025-05-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_centercard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='button_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
