# Generated by Django 5.1.5 on 2025-05-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_product_thumbnail_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='estimated_material_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rough estimate of total material required', max_digits=10, null=True),
        ),
    ]
