# Generated by Django 5.1.5 on 2025-05-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_faq_ourfaqbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='LATEST DESIGN', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('button_text', models.CharField(default='Shop Now', max_length=100)),
                ('button_link', models.URLField(default='#')),
                ('image', models.ImageField(upload_to='center_cards/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
