# Generated by Django 5.1.3 on 2025-05-31 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_centercard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=255)),
                ('adminid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyRegSupplier',
            fields=[
                ('prs_slid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('prs_name', models.CharField(max_length=50)),
                ('prs_address', models.CharField(max_length=50)),
                ('prs_person', models.CharField(max_length=50)),
                ('prs_mobile', models.CharField(max_length=50)),
                ('prs_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('prs_email', models.CharField(blank=True, max_length=50, null=True)),
                ('prs_website', models.CharField(blank=True, max_length=50, null=True)),
                ('prs_complain_number', models.CharField(blank=True, max_length=20, null=True)),
                ('prs_reg_date', models.CharField(blank=True, max_length=10, null=True)),
                ('loginidno', models.CharField(blank=True, max_length=25, null=True)),
                ('open_sdue', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mr_material_name', models.CharField(max_length=255)),
                ('mr_material_details', models.TextField(blank=True, null=True)),
                ('mr_buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mr_sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adminid', models.IntegerField(blank=True, null=True)),
                ('mr_type', models.ForeignKey(db_column='mr_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.materialtype')),
                ('mr_supplier', models.ForeignKey(db_column='mr_supplier_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.partyregsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInventoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_invoice_id', models.CharField(max_length=100)),
                ('mid_buy_quentity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mid_buy_prices', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mid_buy_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mid_sell_quentity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mid_sell_prices', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mid_sell_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mid_exp_date', models.DateField(blank=True, null=True)),
                ('mid_entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('mid_deal_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('adminid', models.IntegerField(blank=True, null=True)),
                ('due_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mid_entry_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_inventory', to=settings.AUTH_USER_MODEL)),
                ('mid_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='backend.materialregistration')),
                ('mid_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_details', to='backend.partyregsupplier')),
            ],
        ),
    ]
