# Generated by Django 5.1.3 on 2025-05-31 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_materialtype_partyregsupplier_materialregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvWarehouse',
            fields=[
                ('invw_id', models.AutoField(primary_key=True, serialize=False)),
                ('invw_name', models.CharField(max_length=255)),
                ('invw_code', models.CharField(max_length=100, unique=True)),
                ('invw_address', models.TextField(blank=True, null=True)),
                ('invw_city', models.CharField(blank=True, max_length=100, null=True)),
                ('invw_state', models.CharField(blank=True, max_length=100, null=True)),
                ('invw_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('invw_country', models.CharField(blank=True, max_length=100, null=True)),
                ('invw_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('invw_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('invw_contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('invw_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('invw_created_at', models.DateTimeField(auto_now_add=True)),
                ('invw_updated_at', models.DateTimeField(auto_now=True)),
                ('invw_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses_created', to=settings.AUTH_USER_MODEL)),
                ('invw_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses_updated', to=settings.AUTH_USER_MODEL)),
                ('invw_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_warehouse',
            },
        ),
    ]
