# Generated by Django 5.1.5 on 2025-06-01 07:32

import backend.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_invwarehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.CharField(max_length=50)),
                ('CustomerName', models.CharField(max_length=50)),
                ('CustomerAddress', models.CharField(max_length=250)),
                ('CustomerEmail', models.CharField(max_length=25, null=True)),
                ('CustomerContact', models.CharField(max_length=25)),
                ('RegDate', models.DateField()),
                ('dabite', models.CharField(max_length=100, null=True)),
                ('cradit', models.CharField(max_length=100, null=True)),
                ('adminid', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=25, null=True)),
                ('open_due', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer_info',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='materialinventorydetail',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.order'),
        ),
        migrations.AddField(
            model_name='materialregistration',
            name='mr_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=backend.models.banner_image_upload_path),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='backend.measurement')),
            ],
        ),
    ]
