# Generated by Django 5.1.5 on 2025-06-01 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_customerinfo_measurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='measurement',
        ),
        migrations.AddField(
            model_name='measurement',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.product'),
        ),
    ]
