# Generated by Django 5.1.5 on 2025-06-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_remove_unit_measurement_measurement_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialregistration',
            name='unit',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='backend.unit'),
            preserve_default=False,
        ),
    ]
