# Generated by Django 5.1.5 on 2025-06-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_materialregistration_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(upload_to='Blog_banner/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(default='BEST SELLER PRODUCTS', max_length=255)),
                ('title', models.CharField(default='Discover Our Best Selling Product You Need', max_length=255)),
                ('button_text', models.CharField(default='Make an Order', max_length=100)),
                ('button_link', models.CharField(default='#', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/cta/')),
            ],
        ),
        migrations.CreateModel(
            name='PricingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(default='GET 30% OFF TODAY', max_length=255)),
                ('title', models.CharField(default='Nice Colorful Bag Printing', max_length=255)),
                ('price_text', models.CharField(default='Start selling', max_length=255)),
                ('price_value', models.CharField(default='$235.00', max_length=100)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.CharField(default='#', max_length=255)),
                ('image', models.ImageField(upload_to='pricing_card/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(upload_to='contact_banner/')),
            ],
        ),
    ]
