# Generated by Django 5.1.5 on 2025-06-02 08:58

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_blogbanner_homecta_pricingcard_productbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Blog content with rich text editor', max_length=5000)),
                ('image', models.ImageField(help_text='Blog thumbnail image', upload_to='blog/')),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Select product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='backend.product')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
