# Generated by Django 5.1.5 on 2025-06-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='comment',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='message',
            field=models.TextField(default='No message', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='number',
            field=models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.blogpost'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
