# Generated by Django 5.1.5 on 2025-06-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_materialusage_unit_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
