# Generated by Django 5.1.5 on 2025-06-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialinventorydetail',
            name='mid_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='materialinventorydetail',
            name='mid_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
