# Generated by Django 5.1.5 on 2025-06-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_discountcategory_product_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialinventorydetail',
            name='id_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='materialinventorydetail',
            name='mid_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
