# Generated by Django 5.1.5 on 2025-06-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
