# Generated by Django 5.1.3 on 2025-06-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_remove_blogcomment_comment_blogcomment_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Processing'), (3, 'Completed'), (4, 'Cancelled'), (5, 'Not Viewed')], default='pending', max_length=20),
        ),
    ]
