# Generated by Django 5.1.5 on 2025-06-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_cartbanner_alter_order_status_addcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
