# Generated by Django 5.1.5 on 2025-06-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialusage',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usages', to='backend.orderitem'),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.materialregistration'),
        ),
    ]
