# Generated by Django 5.1.5 on 2025-06-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_checkoutbanner_ordersummary_orderitemsummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorylog',
            options={'verbose_name': 'Inv Log', 'verbose_name_plural': 'Inv Logs'},
        ),
        migrations.AlterModelOptions(
            name='invwarehouse',
            options={'verbose_name': 'Inv Warehouse', 'verbose_name_plural': 'Inv Warehouse'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Inv Material', 'verbose_name_plural': 'Inv Materials'},
        ),
        migrations.AlterModelOptions(
            name='materialinventorydetail',
            options={'verbose_name': 'Inv Material Details ', 'verbose_name_plural': 'Inv Material Details'},
        ),
        migrations.AlterModelOptions(
            name='materialregistration',
            options={'verbose_name': 'Inv Material Registration ', 'verbose_name_plural': 'Inv Material Registration'},
        ),
        migrations.AlterModelOptions(
            name='materialtype',
            options={'verbose_name': 'Inv Material Type', 'verbose_name_plural': 'Inv Material Types'},
        ),
        migrations.AlterModelOptions(
            name='materialusage',
            options={'verbose_name': 'Inv Material Usage ', 'verbose_name_plural': 'Inv Material Usage'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Inv Measurement', 'verbose_name_plural': 'Inv Measurements'},
        ),
        migrations.AlterModelOptions(
            name='measurementtype',
            options={'verbose_name': 'Inv Measurement Type', 'verbose_name_plural': 'Inv Measurement Types'},
        ),
        migrations.AlterModelOptions(
            name='measurementunit',
            options={'verbose_name': 'Inv Measurement Unit', 'verbose_name_plural': 'Inv Measurement Units'},
        ),
        migrations.AlterModelOptions(
            name='orderspecification',
            options={'verbose_name': 'Inv Order Specification', 'verbose_name_plural': 'Inv Order Specifications'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Inv Product', 'verbose_name_plural': 'Inv Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Inv Product Image', 'verbose_name_plural': 'Inv Products Images'},
        ),
        migrations.AlterModelOptions(
            name='productmaterial',
            options={'verbose_name': 'Inv Product Material', 'verbose_name_plural': 'Inv Product Materials'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Inv Unit', 'verbose_name_plural': 'Inv Units'},
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='district_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='district_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='thana_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='thana_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('flat_rate', 'Flat Rate (৳100)'), ('free_shipping', 'Free Shipping')], default='flat_rate', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
