# Generated by Django 5.1.5 on 2025-06-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_alter_inventorylog_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialinventorydetail',
            old_name='adminid',
            new_name='mid_adminid',
        ),
        migrations.RenameField(
            model_name='materialinventorydetail',
            old_name='due_discount',
            new_name='mid_debit',
        ),
        migrations.RenameField(
            model_name='materialinventorydetail',
            old_name='id_debit',
            new_name='mid_due_discount',
        ),
        migrations.RenameField(
            model_name='materialinventorydetail',
            old_name='order_id',
            new_name='mid_order_id',
        ),
        migrations.AlterField(
            model_name='materialinventorydetail',
            name='mid_party',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
