# Generated by Django 5.1.5 on 2025-06-17 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_rename_adminid_materialinventorydetail_mid_adminid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinventorydetail',
            name='mid_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='backend.materialregistration'),
        ),
    ]
