# Generated by Django 5.1.5 on 2025-06-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_alter_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchViewBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(upload_to='search_banner/')),
            ],
        ),
    ]
