# Generated by Django 5.1.5 on 2025-06-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_thankyoubanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlocation',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactlocation',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
