# Generated by Django 5.1.5 on 2025-06-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_thankyoubanner_remove_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
