# Generated by Django 5.1.5 on 2025-06-19 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_contactlocation_email_contactlocation_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_type', models.CharField(max_length=50)),
                ('m_brand', models.CharField(max_length=50)),
                ('m_model', models.CharField(max_length=50)),
                ('m_purchase_date', models.DateField()),
                ('m_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_description', models.TextField()),
                ('md_serial_number', models.CharField(max_length=100)),
                ('md_capacity', models.CharField(max_length=100)),
                ('md_location', models.CharField(max_length=100)),
                ('md_last_service_date', models.DateField(blank=True, null=True)),
                ('md_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='backend.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='machine_images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='machine_images/thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.machine')),
            ],
        ),
    ]
