# Generated by Django 5.1.5 on 2025-06-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_machine_machinedetails_machineimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(help_text="Use values like 'list' or 'detail'", max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='machine_banners/')),
            ],
        ),
    ]
