# Generated by Django 5.1.5 on 2025-06-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_machinebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
