# Generated by Django 5.1.5 on 2025-06-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_addcart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog/videos/'),
        ),
    ]
