# Generated by Django 5.1.5 on 2025-06-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_blogpost_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
