# Generated by Django 5.1.5 on 2025-06-22 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, help_text='Specify district name or leave blank for default cost', max_length=50, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='backend.shippingcosttype')),
            ],
            options={
                'verbose_name': 'Shipping Cost',
                'verbose_name_plural': 'Shipping Costs',
                'unique_together': {('shipping_type', 'district')},
            },
        ),
    ]
