# Generated by Django 5.1.5 on 2025-06-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_shippingcosttype_shippingcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_type_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
