# Generated by Django 5.1.5 on 2025-06-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_permissioncategory_custompermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialusage',
            unique_together={('order_item', 'material')},
        ),
    ]
