# Generated by Django 5.1.5 on 2025-06-24 06:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_alter_materialusage_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Blog content with rich text editor'),
        ),
    ]
