# Generated by Django 5.1.5 on 2025-06-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_alter_blogpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='m_brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='m_model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='m_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='m_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='m_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machinedetails',
            name='md_capacity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machinedetails',
            name='md_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='machinedetails',
            name='md_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machinedetails',
            name='md_serial_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
