# Generated by Django 5.1.5 on 2025-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_alter_machine_m_brand_alter_machine_m_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='button_link',
            field=models.CharField(max_length=200),
        ),
    ]
